calendrier:
    path: /
    controller: App\Controller\DefaultController::index

add_user:
    path: /add_user
    controller: App\Controller\UserController::new

consult_users:
    path : /consult_users
    controller: App\Controller\UserController::index

ModificationPlanning:
  path: /ModificationPlanning
  controller: App\Controller\ModificationPlanningController::modificationPlanningGet

index_patients:
    path : /patients
    controller: App\Controller\PatientController::index

index_activities:
    path : /activities
    controller: App\Controller\ActivityController:index

index_circuits:
    path : /circuits
    controller: App\Controller\CircuitController:index
    
index_type_circuits:
    path : /type-circuits
    controller: App\Controller\CircuitTypeController:index

