calendrier:
  path: /
  controller: App\Controller\ConsultationPlanningController::consultationPlanningGet

add_user:
  path: /add_user
  controller: App\Controller\UserController::new

consult_users:
  path: /consult_users
  controller: App\Controller\UserController::index

ConsultationPlanning:
  path: /ConsultationPlanning
  controller: App\Controller\ConsultationPlanningController::consultationPlanningGet

Connexion:
  path: /connexion
  controller: App\Controller\ConnexionController::afficherPage
  methods: [GET]

ConnexionPost:
  path: /connexion
  controller: App\Controller\ConnexionController::connexionPost
  methods: [POST]

ModificationPlanning:
  path: /ModificationPlanning
  controller: App\Controller\ModificationPlanningController::modificationPlanningGet
  methods: [GET]

ModificationPlanningPost:
  path: /ModificationPlanning
  controller: App\Controller\ModificationPlanningController::modificationPlanningPost
  methods: [POST]

index_patients:
  path: /patients
  controller: App\Controller\PatientController::index



app_activity_index:
  path: /activities
  controller: App\Controller\ActivityController:index

Pathways:
  path: /pathways
  controller: App\Controller\PathwayController:index
  methods: [GET]

PathwaysPost:
  path: /pathways
  controller: App\Controller\PathwayController:new
  methods: [POST]

index_resources:
  path: /resources
  controller: App\Controller\HumanResourceController:index

index_resources_types:
  path: /resources-types
  controller: App\Controller\ResourceTypeController:index

index_resources_types_humans:
  path: /resources-types-humans
  controller: App\Controller\ResourceTypeController:indexFilteredHumans

index_resources_types_materials:
  path: /resources-types-materials
  controller: App\Controller\ResourceTypeController:indexFilteredMaterials

index_mon_profil:
  path: /mon_profil
  controller: App\Controller\UserController:edit

app_activity_new:
  path: /activities/new
  controller: App\Controller\ActivityController:new
  methods: [POST]