calendrier:
  path: /
  controller: App\Controller\ConsultationPlanningController::consultationPlanningGet

add_user:
  path: /add_user
  controller: App\Controller\UserController::new

consult_users:
  path: /consult_users
  controller: App\Controller\UserController::index

ConsultationPlanning:
  path: /ConsultationPlanning
  controller: App\Controller\ConsultationPlanningController::consultationPlanningGet

Connexion:
  path: /connexion
  controller: App\Controller\ConnexionController::afficherPage
  methods: [GET]

ConnexionPost:
  path: /connexion
  controller: App\Controller\ConnexionController::connexionPost
  methods: [POST]

ModificationPlanning:
  path: /ModificationPlanning
  controller: App\Controller\ModificationPlanningController::modificationPlanningGet
  methods: [GET]

ModificationPlanningPost:
  path: /ModificationPlanning
  controller: App\Controller\ModificationPlanningController::modificationPlanningPost
  methods: [POST]

Patients:
  path: /patients
  controller: App\Controller\PatientController::patientGet
  methods: [GET]

PatientsPost:
  path: /patients
  controller: App\Controller\PatientController::patientPost
  methods: [POST]

PatientDelete:
  path: /patient/{id}/delete
  controller: App\Controller\PatientController::patientDelete
  methods: [POST]

PatientEdit:
  path: /patient/edit
  controller: App\Controller\PatientController::patientEdit
  methods: [POST]

Appointment:
  path: /appointments
  controller: App\Controller\AppointmentController::appointmentGet
  methods: [GET]

AppointmentPost:
  path: /appointments
  controller: App\Controller\AppointmentController::appointmentPost
  methods: [POST]

app_activity_index:
  path: /activities
  controller: App\Controller\ActivityController:index

Pathways:
  path: /pathways
  controller: App\Controller\PathwayController:index
  methods: [GET]

PathwaysPost:
  path: /pathways
  controller: App\Controller\PathwayController:new
  methods: [POST]

index_human_resources:
  path: /human-resources
  controller: App\Controller\HumanResourceController:index

index_material_resources:
  path: /material-resources
  controller: App\Controller\MaterialResourceController:index

index_mon_profil:
  path: /mon_profil
  controller: App\Controller\UserController:edit

app_activity_new:
  path: /activities/new
  controller: App\Controller\ActivityController:new
  methods: [POST]