#index:
#    path: /
#    controller: App\Controller\DefaultController::index
add_user:
    path: /add_user
    controller: App\Controller\UserController::new

consult_users:
    path : /consult_users
    controller: App\Controller\UserController::index