add_user:
  path: /add_user
  controller: App\Controller\UserController::new

consult_users:
  path: /consult_users
  controller: App\Controller\UserController::index

ConsultationPlanning:
  path: /ConsultationPlanning
  controller: App\Controller\ConsultationPlanningController::consultationPlanningGet

Connexion:
  path: /connexion
  controller: App\Controller\ConnexionController::afficherPage
  methods: [GET]

ConnexionPost:
  path: /connexion
  controller: App\Controller\ConnexionController::connexionPost
  methods: [POST]

ModificationPlanning:
  path: /ModificationPlanning
  controller: App\Controller\ModificationPlanningController::modificationPlanningGet
  methods: [GET]

ModificationPlanningPost:
  path: /ModificationPlanning
  controller: App\Controller\ModificationPlanningController::modificationPlanningPost
  methods: [POST]

ModificationPlanningValidation:
  path: /ModificationPlanningValidation
  controller: App\Controller\ModificationPlanningController::modificationPlanningValidation
  methods: [POST]

ModificationDeleteOnUnload:
  path: /ModificationDeleteOnUnload
  controller: App\Controller\ModificationPlanningController::modificationDeleteOnUnload
  methods: [GET]
  
Patients:
  path: /patients
  controller: App\Controller\PatientController::patientGet
  methods: [GET]

PatientAdd:
  path: /patients
  controller: App\Controller\PatientController::patientAdd
  methods: [POST]

PatientDelete:
  path: /patient/{id}/delete
  controller: App\Controller\PatientController::patientDelete
  methods: [POST]

PatientEdit:
  path: /patient/edit
  controller: App\Controller\PatientController::patientEdit
  methods: [POST]

User:
  path: /user
  controller: App\Controller\UserController::userGet
  methods: [GET]

UserAdd:
  path: /userAdd
  controller: App\Controller\UserController::userAdd
  methods: [POST]

UserDelete:
  path: /user/{id}/delete
  controller: App\Controller\UserController::userDelete
  methods: [POST]

UserEdit:
  path: /user/edit
  controller: App\Controller\UserController::userEdit
  methods: [POST]

Profil:
  path: /profil
  controller: App\Controller\ProfilController::profilGet
  methods: [GET]

ProfilEdit:
  path: /profil
  controller: App\Controller\ProfilController::profilEdit
  methods: [POST]

MaterialResourceCategoryEdit:
  path: /material-category/edit
  controller: App\Controller\MaterialResourceCategoryController::edit
  methods: [POST]

HumanResourceCategoryEdit:
  path: /human-category/edit
  controller: App\Controller\HumanResourceCategoryController::edit
  methods: [POST]

Appointment:
  path: /appointments
  controller: App\Controller\AppointmentController::appointmentGet
  methods: [GET]

AppointmentAdd:
  path: /appointmentAdd
  controller: App\Controller\AppointmentController::appointmentAdd
  methods: [POST]

AppointmentDelete:
  path: /appointment/{id}/delete
  controller: App\Controller\AppointmentController::appointmentDelete
  methods: [POST]

AppointmentEdit:
  path: /appointment/edit
  controller: App\Controller\AppointmentController::appointmentEdit
  methods: [POST]

Pathways:
  path: /pathways
  controller: App\Controller\PathwayController:pathwayGet
  methods: [GET]

PathwayAdd:
  path: /pathway/add
  controller: App\Controller\PathwayController:pathwayAdd
  methods: [POST]

PathwayAddPage:
  path: /pathway/add
  controller: App\Controller\PathwayController:pathwayAddPage
  methods: [GET]

PathwayEditPage:
  path: /pathway/edit/{id}
  controller: App\Controller\PathwayController:pathwayEditPage
  methods: [GET]

PathwayEdit:
  path: /pathway/edit
  controller: App\Controller\PathwayController:pathwayEdit
  methods: [POST]

PathwayDelete:
  path: /pathway/delete
  controller: App\Controller\PathwayController:pathwayDelete
  methods: [POST]

HumanResourceEdit:
  path: /human-resource/edit
  controller: App\Controller\HumanResourceController::edit
  methods: [POST]

HumanResourceUnavailability:
  path: /human-resource/unavailability
  controller: App\Controller\HumanResourceController::unavailability
  methods: [POST]

MaterialResourceUnavailability:
  path: /material-resource/unavailability
  controller: App\Controller\MaterialResourceController::unavailability
  methods: [POST]

MaterialResourceEdit:
  path: /material-resource/edit
  controller: App\Controller\MaterialResourceController::edit
  methods: [POST]

HumanResPost:
  path: /human-resources
  controller: App\Controller\HumanResourceController:new
  methods: [POST]

MaterialResPost:
  path: /material-resources
  controller: App\Controller\MaterialResourceController:new
  methods: [POST]

index_human_resources:
  path: /human-resources
  controller: App\Controller\HumanResourceController:index

index_material_resources:
  path: /material-resources
  controller: App\Controller\MaterialResourceController:index

index_mon_profil:
  path: /mon_profil
  controller: App\Controller\UserController:edit

Settings:
  path: /settings
  controller: App\Controller\SettingsController:settingsGet
  methods: [GET]

SettingsEdit:
  path: /settings/edit
  controller: App\Controller\SettingsController:settingsEdit
  methods: [POST]

SettingsAddDefault:
  path: /settings/addDefault
  controller: App\Controller\SettingsController:settingsAddDefault
  methods: [POST]

AjaxAppointment:
  path: /ajaxAppointment
  controller: App\Controller\AppointmentController::getTargets
  methods: [POST]

AjaxPatient:
  path: /ajaxPatient
  controller: App\Controller\PatientController::getDataPatient
  methods: [POST]

AjaxPathwayAppointments:
  path: /ajaxPathwayAppointments
  controller: App\Controller\PathwayController::getAppointmentsByPathwayId
  methods: [POST]

AjaxPathwayActivities:
  path: /ajaxPathwayActivities
  controller: App\Controller\PathwayController::getActivitiesByPathwayId
  methods: [POST]

AjaxHumanResource:
  path: /ajaxHumanResource
  controller: App\Controller\HumanResourceController::getDataHumanResource
  methods: [POST]

AjaxMaterialResource:
  path: /ajaxMaterialResource
  controller: App\Controller\MaterialResourceController::getDataMaterialResource
  methods: [POST]