calendrier:
  path: /
  controller: App\Controller\ConsultationPlanningController::consultationPlanningGet

add_user:
  path: /add_user
  controller: App\Controller\UserController::new

consult_users:
  path: /consult_users
  controller: App\Controller\UserController::index

ConsultationPlanning:
  path: /ConsultationPlanning
  controller: App\Controller\ConsultationPlanningController::consultationPlanningGet

Connexion:
  path: /connexion
  controller: App\Controller\ConnexionController::afficherPage
  methods: [GET]

ConnexionPost:
  path: /connexion
  controller: App\Controller\ConnexionController::connexionPost
  methods: [POST]

ModificationPlanning:
  path: /ModificationPlanning
  controller: App\Controller\ModificationPlanningController::modificationPlanningGet
  methods: [GET]

ModificationPlanningPost:
  path: /ModificationPlanning
  controller: App\Controller\ModificationPlanningController::modificationPlanningPost
  methods: [POST]

ModificationPlanningValidation:
  path: /ModificationPlanningValidation
  controller: App\Controller\ModificationPlanningController::modificationPlanningValidation
  methods: [POST]

Patients:
  path: /patients
  controller: App\Controller\PatientController::patientGet
  methods: [GET]

PatientAdd:
  path: /patients
  controller: App\Controller\PatientController::patientAdd
  methods: [POST]

PatientDelete:
  path: /patient/{id}/delete
  controller: App\Controller\PatientController::patientDelete
  methods: [POST]

PatientEdit:
  path: /patient/edit
  controller: App\Controller\PatientController::patientEdit
  methods: [POST]

MaterialResourceCategoryEdit:
  path: /material-category/edit
  controller: App\Controller\MaterialResourceCategoryController::edit
  methods: [POST]

HumanResourceCategoryEdit:
  path: /human-category/edit
  controller: App\Controller\HumanResourceCategoryController::edit
  methods: [POST]

Appointment:
  path: /appointments
  controller: App\Controller\AppointmentController::appointmentGet
  methods: [GET]

AppointmentAdd:
  path: /appointmentAdd
  controller: App\Controller\AppointmentController::appointmentAdd
  methods: [POST]

AppointmentDelete:
  path: /appointment/{id}/delete
  controller: App\Controller\AppointmentController::appointmentDelete
  methods: [POST]

AppointmentEdit:
  path: /appointment/edit
  controller: App\Controller\AppointmentController::appointmentEdit
  methods: [POST]

app_activity_index:
  path: /activities
  controller: App\Controller\ActivityController:index

Pathways:
  path: /pathways
  controller: App\Controller\PathwayController:index
  methods: [GET]

PathwaysPost:
  path: /pathways
  controller: App\Controller\PathwayController:new
  methods: [POST]


PathwayEdit:
  path: /pathway/edit
  controller: App\Controller\PathwayController:edit
  methods: [POST]

HumanResPost:
  path: /human-resources
  controller: App\Controller\HumanResourceController:new
  methods: [POST]

MaterialResPost:
  path: /material-resources
  controller: App\Controller\MaterialResourceController:new
  methods: [POST]

index_human_resources:
  path: /human-resources
  controller: App\Controller\HumanResourceController:index

index_material_resources:
  path: /material-resources
  controller: App\Controller\MaterialResourceController:index

index_mon_profil:
  path: /mon_profil
  controller: App\Controller\UserController:edit

app_activity_new:
  path: /activities/new
  controller: App\Controller\ActivityController:new
  methods: [POST]